apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: apicurio-registry
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: apicurio-registry
    app.kubernetes.io/part-of: test-application
  name: apicurio-registry
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: apicurio-registry
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: apicurio-registry
    spec:
      containers:
      - image: quay.io/mkovarik/apicurio-registry
        imagePullPolicy: Always
        name: container-image
        resources: {}
status: {}
