apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  creationTimestamp: null
  name: apicurio-registry
  namespace: test
spec:
  params:
  - name: git-revision
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      annotations:
        build.appstudio.openshift.io/application: test-application
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/component: apicurio-registry
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      creationTimestamp: null
      generateName: apicurio-registry-
      labels:
        build.appstudio.openshift.io/application: test-application
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/component: apicurio-registry
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      namespace: test
    spec:
      params:
      - name: git-url
        value: https://github.com/Michkov/apicurio-registry
      - name: output-image
        value: quay.io/mkovarik/apicurio-registry:latest-$(tt.params.git-revision)
      pipelineRef:
        bundle: quay.io/mkovarik/build-templates-bundle:2022-06-15-130458
        name: java-builder
      workspaces:
      - name: workspace
        persistentVolumeClaim:
          claimName: appstudio
        subPath: apicurio-registry/$(tt.params.git-revision)
      - name: registry-auth
        secret:
          secretName: redhat-appstudio-registry-pull-secret
    status: {}
status: {}
